package report

import (
	"fmt"
	"io"
	"strings"
)

// ApplyInclude names where the generated pipeline finds .blastdoor:apply.
// File alone is a `local:` include (the repository's own file, the original
// and still the default); setting Project switches to `project:`/`ref:`, so a
// shared .blastdoor:apply can be referenced instead of copied per repository.
type ApplyInclude struct {
	File    string
	Project string
	Ref     string
}

func (i ApplyInclude) includeYAML() string {
	if i.Project == "" {
		return "include:\n  - local: " + yamlString(i.File) + "\n"
	}
	var b strings.Builder
	b.WriteString("include:\n  - project: " + yamlString(i.Project) + "\n")
	if i.Ref != "" {
		b.WriteString("    ref: " + yamlString(i.Ref) + "\n")
	}
	b.WriteString("    file: " + yamlString(i.File) + "\n")
	return b.String()
}

// WriteApplyYAML writes a child pipeline whose jobs carry a literal `when:`.
//
// This file exists because GitLab cannot make this decision from a variable.
// `when:` does not expand one, and `rules:` — which can set `when:` — is
// evaluated at pipeline creation, before any job has run, so the dotenv written
// by 'blastdoor eval' is not visible to it. Generating the pipeline is the only
// place the decision can become a literal the runner will honour.
//
// Blastdoor writes the `when:` and nothing else. The image, the credentials and
// the apply command belong to whoever supplies the .blastdoor:apply job named
// by include, and that source must be guarded, because it runs with the
// credentials that change infrastructure.
//
// This always produces a valid child pipeline, even when every environment
// resolved to None: a GitLab child pipeline needs at least one job, or the
// trigger job that would run it fails to create it at all — and there is no
// `rules:` condition able to route around that ahead of time (`rules:` runs
// before this file's own generating job has, the same limitation this file
// exists to work around for `when:`). So an all-None report gets a single
// placeholder job instead of an empty file, and 'blastdoor eval' writes this
// file unconditionally whenever a wish was stated, never omitting it.
func (r Report) WriteApplyYAML(w io.Writer, include ApplyInclude) error {
	var jobs strings.Builder
	any := false
	for _, e := range r.Environments {
		// Nothing to apply, so no job. An empty one would run the repository's
		// apply script against no units, which fails in a way that reads as a
		// broken pipeline rather than as an environment nothing touched.
		if e.Method == None {
			continue
		}

		// Exhaustive, with no default falling through to on_success: a
		// future fourth Method must name its own when: explicitly, rather
		// than silently becoming an unattended apply because nothing here
		// recognised it.
		var when string
		switch e.Method {
		case Auto:
			when = "on_success"
		case Manual:
			when = "manual"
		default:
			return fmt.Errorf("environment %q has method %q, which has no when: mapping", e.Name, e.Method)
		}

		any = true
		fmt.Fprintf(&jobs,
			"\napply:%s:\n  extends: .blastdoor:apply\n  when: %s\n  variables:\n    BLASTDOOR_ENV: %s\n",
			e.Name, when, yamlString(e.Name))
	}

	var b strings.Builder
	b.WriteString("# generated by blastdoor; do not edit\n")

	if !any {
		// Nothing in this change has anything to apply — the ordinary case
		// for a docs-only or CI-only commit. There is no .blastdoor:apply job
		// to extend in this case, so this placeholder does not include the
		// repository's apply file at all: not depending on that file existing
		// is one less way an otherwise-uneventful pipeline can fail.
		b.WriteString("blastdoor:nothing-to-apply:\n  stage: .pre\n  script:\n    - echo \"no environment in this change has anything to apply\"\n")
		_, err := io.WriteString(w, b.String())
		return err
	}

	b.WriteString(include.includeYAML())
	b.WriteString(jobs.String())

	_, err := io.WriteString(w, b.String())
	return err
}

// yamlString quotes a value so it cannot be read as YAML syntax.
//
// Environment names are already restricted to what a dotenv key allows, but the
// include path is an arbitrary string from a flag.
func yamlString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}
