package report

import (
	"fmt"
	"io"
	"strings"
)

// WriteApplyYAML writes a child pipeline whose jobs carry a literal `when:`.
//
// This file exists because GitLab cannot make this decision from a variable.
// `when:` does not expand one, and `rules:` — which can set `when:` — is
// evaluated at pipeline creation, before any job has run, so the dotenv written
// by 'blastdoor eval' is not visible to it. Generating the pipeline is the only
// place the decision can become a literal the runner will honour.
//
// Blastdoor writes the `when:` and nothing else. The image, the credentials and
// the apply command belong to the repository, which supplies them as a hidden
// .blastdoor:apply job in the included file — and that file must be guarded,
// because it runs with the credentials that change infrastructure.
func (r Report) WriteApplyYAML(w io.Writer, include string) error {
	var b strings.Builder
	b.WriteString("# generated by blastdoor; do not edit\n")
	b.WriteString("include:\n  - local: " + yamlString(include) + "\n")

	for _, e := range r.Environments {
		// Nothing to apply, so no job. An empty one would run the repository's
		// apply script against no units, which fails in a way that reads as a
		// broken pipeline rather than as an environment nothing touched.
		if e.Method == None {
			continue
		}

		when := "on_success"
		if e.Method == Manual {
			when = "manual"
		}

		fmt.Fprintf(&b,
			"\napply:%s:\n  extends: .blastdoor:apply\n  when: %s\n  variables:\n    BLASTDOOR_ENV: %s\n",
			e.Name, when, yamlString(e.Name))
	}

	_, err := io.WriteString(w, b.String())
	return err
}

// yamlString quotes a value so it cannot be read as YAML syntax.
//
// Environment names are already restricted to what a dotenv key allows, but the
// include path is an arbitrary string from a flag.
func yamlString(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}
